### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by Mwapsam** [gtekle/leaderboard#4]
**Hi @Tekle,**
We loved your project 💯 and the javascript was very well structured. The code was DRY and you kept it simple.
However, there are a few issues to air out in order to improve your project:
[Optional]

- Consider adding the description on the about on the Github repository to help users easily know what your project is all about.
- To make your code readable, consider using async and await instead of promise in the scores.js.
- Please validate the name input to accept only alphabetical values on the form.

**Comment by gtekle** [comment]
Hi Fatima, Pedro, and Samuel,

Thank you all for the invaluable feedback and I will definitely address each and every one of them.

thanks again
@TimmyChan99 @guerreiropedr0 @Mwapsam

**Comment by gtekle** [comment]
Issues are resolved!
